"""empty message

Revision ID: 4e577bf1caf9
Revises: 
Create Date: 2021-05-17 01:34:33.190272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e577bf1caf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('new_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User') as batch_op:
        batch_op.drop_column('new_field')
    # ### end Alembic commands ###
